name: bmi_test2
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_pagination: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  get_it: ^7.7.0
  shared_preferences: ^2.2.3

dev_dependencies:

  
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
 