// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvg3md2Q7KozDTE8jlCjbxg57Ti2uYbO4',
    appId: '1:111414326598:web:9190299e8f48154c742147',
    messagingSenderId: '111414326598',
    projectId: 'bmi-test-325e9',
    authDomain: 'bmi-test-325e9.firebaseapp.com',
    storageBucket: 'bmi-test-325e9.appspot.com',
    measurementId: 'G-9VL0M6J5SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pJLhw-QOrg7hkrKjE89DEIsgagjdTYI',
    appId: '1:111414326598:android:74901af1720ca4ae742147',
    messagingSenderId: '111414326598',
    projectId: 'bmi-test-325e9',
    storageBucket: 'bmi-test-325e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhEeRpllZeHW3ZuOd-5uiWSUyCYAcHzFI',
    appId: '1:111414326598:ios:9bb6561131d6a910742147',
    messagingSenderId: '111414326598',
    projectId: 'bmi-test-325e9',
    storageBucket: 'bmi-test-325e9.appspot.com',
    iosBundleId: 'com.example.bmiTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhEeRpllZeHW3ZuOd-5uiWSUyCYAcHzFI',
    appId: '1:111414326598:ios:ccc48556a312cda3742147',
    messagingSenderId: '111414326598',
    projectId: 'bmi-test-325e9',
    storageBucket: 'bmi-test-325e9.appspot.com',
    iosBundleId: 'com.example.bmiTest2.RunnerTests',
  );
}
